// 2023 Kentucky Governor - Code 1
// Paste this into the New Campaign Trail Code 1 box, then paste Code 2.
// Soundtrack entries are metadata/search cues only; no copyrighted audio is bundled.
(function () {
  const root = typeof window !== "undefined" ? window : globalThis;
  root.campaignTrail_temp = root.campaignTrail_temp || {};
  const campaignTrail_temp = root.campaignTrail_temp;

  const MOD = {
  "id": 20231107,
  "loader_slot": 20,
  "title": "2023 Kentucky Governor",
  "subtitle": "Beshear vs. Cameron",
  "creator": "Generated by Codex for a New Campaign Trail-style mod",
  "github_raw_base": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main",
  "code2_url": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/code2_2023_ky_governor.js?ky2023=portraits-map-v2",
  "drop_slug": "2023KYGov",
  "asset_urls": {
    "banner": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/ky2023_banner.svg",
    "background": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/ky2023_background.svg",
    "icon": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/ky2023_icon.svg",
    "intro": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/ky2023_intro.jpg",
    "beshear": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/beshear.jpg",
    "cameron": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/cameron.jpg",
    "coleman": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/coleman.jpg",
    "mills": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/mills.jpg",
    "beshear_sign": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/ky2023_beshear_sign.svg",
    "cameron_sign": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/ky2023_cameron_sign.svg"
  },
  "soundtrack": [
    {
      "title": "Last Night",
      "artist": "Morgan Wallen",
      "year": 2023,
      "mood": "rural radio / red-county ad break"
    },
    {
      "title": "Flowers",
      "artist": "Miley Cyrus",
      "year": 2023,
      "mood": "upbeat statewide bumper"
    },
    {
      "title": "Kill Bill",
      "artist": "SZA",
      "year": 2023,
      "mood": "metro turnout montage"
    },
    {
      "title": "Fast Car",
      "artist": "Luke Combs",
      "year": 2023,
      "mood": "working-class crossover"
    },
    {
      "title": "Need a Favor",
      "artist": "Jelly Roll",
      "year": 2023,
      "mood": "recovery / faith / opioid-question bed"
    },
    {
      "title": "I Remember Everything",
      "artist": "Zach Bryan feat. Kacey Musgraves",
      "year": 2023,
      "mood": "closing stretch reflection"
    },
    {
      "title": "Dance the Night",
      "artist": "Dua Lipa",
      "year": 2023,
      "mood": "light election-night menu"
    },
    {
      "title": "vampire",
      "artist": "Olivia Rodrigo",
      "year": 2023,
      "mood": "attack-ad sting"
    },
    {
      "title": "Paint The Town Red",
      "artist": "Doja Cat",
      "year": 2023,
      "mood": "Cameron momentum cue"
    },
    {
      "title": "What Was I Made For?",
      "artist": "Billie Eilish",
      "year": 2023,
      "mood": "melancholy loss ending"
    },
    {
      "title": "Barbie World",
      "artist": "Nicki Minaj & Ice Spice with Aqua",
      "year": 2023,
      "mood": "youth-turnout gag slot"
    },
    {
      "title": "Rich Men North of Richmond",
      "artist": "Oliver Anthony Music",
      "year": 2023,
      "mood": "anti-establishment rural cue"
    }
  ],
  "sources": {
    "2023 Kentucky gubernatorial county results": "https://en.wikipedia.org/wiki/2023_Kentucky_gubernatorial_election",
    "2020 Kentucky presidential county results": "https://en.wikipedia.org/wiki/2020_United_States_presidential_election_in_Kentucky",
    "U.S. county GeoJSON boundaries": "https://github.com/plotly/datasets/blob/master/geojson-counties-fips.json",
    "AP Beshear path analysis": "https://apnews.com/article/f942a360de22975335a1406f1fdd9ad4"
  }
};
  root.KY2023_CODE1 = MOD;
  root.e = campaignTrail_temp;

  campaignTrail_temp.election_id = 20;
  campaignTrail_temp.election_json = [
  {
    "model": "campaign_trail.election",
    "pk": 20,
    "fields": {
      "year": 2023,
      "display_year": "2023 Kentucky Governor",
      "summary": "<p>Incumbent Democratic Governor Andy Beshear seeks a second term in a state Donald Trump carried by about 26 points in 2020. Republican Attorney General Daniel Cameron tries to nationalize the race around Biden, inflation, crime, schools, and conservative control of Frankfort. Beshear counters with disaster response, economic development, abortion exceptions, and a Kentucky-first personal brand.</p>",
      "image_url": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/ky2023_intro.jpg",
      "site_image": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/ky2023_icon.svg",
      "site_description": "A two-sided 2023 Kentucky governor mod with county-level baselines, Kentucky issue maps, and a state-race presentation.",
      "winning_electoral_vote_number": 675,
      "advisor_url": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/ky2023_intro.jpg",
      "recommended_reading": "<ul><li>2023 Kentucky gubernatorial election county results</li><li>2020 Kentucky presidential county margins</li><li>AP analysis of Beshear's 2023 path through Trump country</li></ul>",
      "has_visits": 0,
      "no_electoral_majority_image": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/ky2023_intro.jpg"
    }
  }
];
  campaignTrail_temp.candidate_json = [
  {
    "model": "campaign_trail.candidate",
    "pk": 201,
    "fields": {
      "first_name": "Andy",
      "last_name": "Beshear",
      "election": 20,
      "party": "Democratic",
      "state": "Kentucky",
      "priority": 1,
      "description": "<li><b>Name: Andy Beshear</b></li><li><b>Party: Democratic Party</b></li><li><b>Current Office: Governor of Kentucky</b></li><li><b>Home Base: Louisville / Frankfort</b></li><p>Andy Beshear is the incumbent Democratic governor trying to win a second term in a heavily Republican state. His path depends on keeping huge margins in Louisville and Lexington, overperforming in Northern Kentucky and the Bluegrass, and limiting the damage in eastern and western Kentucky.</p><p>To win, Beshear must keep the race local: disaster response, economic development, teacher support, abortion exceptions, and a Kentucky-first personal brand that gives Republicans permission to split their tickets.</p>",
      "color_hex": "#2f6fdd",
      "secondary_color_hex": "#9cc5ff",
      "is_active": 1,
      "image_url": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/beshear.jpg",
      "electoral_victory_message": "<h3>Beshear wins reelection.</h3><p>Kentucky has split its ticket again, rewarding a governor whose personal brand outran federal partisanship.</p>",
      "electoral_loss_message": "<h3>Beshear falls short.</h3><p>Cameron nationalized the race just enough to restore Kentucky's Republican gravity.</p>",
      "no_electoral_majority_message": "<h3>Too close to call.</h3><p>Kentucky is staring at another county-by-county nail-biter.</p>",
      "description_as_running_mate": "<p>Andy Beshear is the top of the Democratic ticket.</p>",
      "candidate_score": 1.0
    }
  },
  {
    "model": "campaign_trail.candidate",
    "pk": 200,
    "fields": {
      "first_name": "Daniel",
      "last_name": "Cameron",
      "election": 20,
      "party": "Republican",
      "state": "Kentucky",
      "priority": 2,
      "description": "<li><b>Name: Daniel Cameron</b></li><li><b>Party: Republican Party</b></li><li><b>Current Office: Kentucky Attorney General</b></li><li><b>County: Hardin County</b></li><p>Daniel Cameron is Kentucky's Republican attorney general and the GOP nominee for governor. He enters the general election with a deep partisan advantage beneath him, but faces an incumbent Democrat whose personal approval has repeatedly outrun national party labels.</p><p>To win, Cameron must make the race about change, affordability, public safety, schools, and Biden-era national politics without letting Beshear turn the election into a referendum on disaster response, abortion exceptions, and local competence.</p>",
      "color_hex": "#c83e3a",
      "secondary_color_hex": "#f4aaa3",
      "is_active": 1,
      "image_url": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/cameron.jpg",
      "electoral_victory_message": "<h3>Cameron wins.</h3><p>Republicans have broken the Beshear coalition and unified Frankfort behind conservative control.</p>",
      "electoral_loss_message": "<h3>Cameron loses.</h3><p>Beshear's personal appeal, disaster response, and suburban crossover vote survived the partisan headwinds.</p>",
      "no_electoral_majority_message": "<h3>Too close to call.</h3><p>The governor race is balanced on a handful of counties.</p>",
      "description_as_running_mate": "<p>Daniel Cameron is the top of the Republican ticket.</p>",
      "candidate_score": 1.0
    }
  },
  {
    "model": "campaign_trail.candidate",
    "pk": 209,
    "fields": {
      "first_name": "Jacqueline",
      "last_name": "Coleman",
      "election": 20,
      "party": "Democratic",
      "state": "Kentucky",
      "priority": 3,
      "description": "'",
      "color_hex": "#2f6fdd",
      "secondary_color_hex": "#9cc5ff",
      "is_active": 0,
      "image_url": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/coleman.jpg",
      "electoral_victory_message": "'",
      "electoral_loss_message": "'",
      "no_electoral_majority_message": "'",
      "description_as_running_mate": "<li><b>Name: Jacqueline Coleman</b></li><li><b>Party: Democratic Party</b></li><li><b>Current Office: Lieutenant Governor of Kentucky</b></li><li><b>Home Base: Harrodsburg / Frankfort</b></li><p>Jacqueline Coleman is the incumbent lieutenant governor, a former teacher, and a strong validator on education, families, and continuity. She helps Beshear reinforce the public-school and empathy side of the ticket while keeping the campaign rooted in Kentucky rather than Washington.</p>",
      "candidate_score": 0.0
    }
  },
  {
    "model": "campaign_trail.candidate",
    "pk": 204,
    "fields": {
      "first_name": "Robby",
      "last_name": "Mills",
      "election": 20,
      "party": "Republican",
      "state": "Kentucky",
      "priority": 4,
      "description": "'",
      "color_hex": "#c83e3a",
      "secondary_color_hex": "#f4aaa3",
      "is_active": 0,
      "image_url": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/assets/images/mills.jpg",
      "electoral_victory_message": "'",
      "electoral_loss_message": "'",
      "no_electoral_majority_message": "'",
      "description_as_running_mate": "<li><b>Name: Robby Mills</b></li><li><b>Party: Republican Party</b></li><li><b>Current Office: Kentucky State Senator</b></li><li><b>County: Henderson County</b></li><p>Robby Mills is a Republican state senator and Cameron's running mate. He gives the ticket a western Kentucky base, legislative relationships, and a pro-business conservative profile that can reassure Republicans who want a governing team ready for Frankfort.</p>",
      "candidate_score": 0.0
    }
  }
];
  campaignTrail_temp.running_mate_json = [
  {
    "model": "campaign_trail.running_mate",
    "pk": 72001,
    "fields": {
      "candidate": 201,
      "running_mate": 209
    }
  },
  {
    "model": "campaign_trail.running_mate",
    "pk": 72002,
    "fields": {
      "candidate": 200,
      "running_mate": 204
    }
  }
];
  campaignTrail_temp.opponents_default_json = [
  {
    "election": 20,
    "candidates": [
      201,
      200
    ]
  }
];
  campaignTrail_temp.opponents_weighted_json = [
  {
    "election": 20,
    "candidates": [
      201,
      200
    ]
  }
];
  campaignTrail_temp.temp_election_list = [
  {
    "id": 20,
    "year": 2023,
    "is_premium": 0,
    "display_year": "2023 KY Governor"
  }
];
  campaignTrail_temp.candidate_dropout_json = [];
  campaignTrail_temp.show_premium = true;
  campaignTrail_temp.premier_ab_test_version = -1;

  root.jet_data = {
    headerColor: "#28318f",
    windowColor: "#646fd4",
    containerColor: "#646fd4",
    innerWindowColor: "#ffffff",
    bannerImageUrl: MOD.asset_urls.banner,
    backgroundImageUrl: MOD.asset_urls.background,
    endingTextColor: "#111827",
    customQuote: "United we stand, divided we fall."
  };
  root.corrr = '<h2>THE KENTUCKY TRAIL</h2><font id="wittyquote" size="4" color="white"><em>United we stand, divided we fall.</em></font>';
  root.HistHexcolour = ["#2f6fdd", "#c83e3a", "#777777", "#ffffff"];
  root.HistName = ["Andy Beshear", "Daniel Cameron", "Write-ins", " "];
  root.HistEV = ["29 counties", "91 counties", "0 counties", " "];
  root.HistPV = ["694,482", "627,457", "83", " "];
  root.HistPVP = ["52.53%", "47.46%", "0.01%", " "];

  campaignTrail_temp.ky2023CreditsPage = function () {
    const doc = root.document;
    const gameWindow = doc && doc.getElementById("game_window");
    if (!gameWindow) return;
    gameWindow.innerHTML = '<div class="game_header">' + root.corrr + '</div>' +
      '<div class="inner_window" style="background:#f8fafc;color:#111827;padding:20px;line-height:1.45;">' +
      '<h2>2023 Kentucky Governor</h2>' +
      '<p><strong>Playable tickets:</strong> Andy Beshear / Jacqueline Coleman and Daniel Cameron / Robby Mills.</p>' +
      '<p><strong>Scenario design:</strong> 25-question Kentucky governor race with county-level baselines, county issue maps, modelled answer swings, endings, and 2023 soundtrack metadata.</p>' +
      '<p><strong>Data:</strong> public 2023 Kentucky gubernatorial county returns, 2020 presidential county margins, U.S. county GeoJSON boundaries, and AP-style post-election path analysis.</p>' +
      '<p><strong>Mod packaging:</strong> Custom-loader Code 1/Code 2 plus a drop-style static folder using the <code>2023KYGov</code> naming convention.</p>' +
      '<p style="text-align:center;"><button onclick="location.reload()">Back</button></p>' +
      '</div>';
  };
  root.ky2023CreditsPage = campaignTrail_temp.ky2023CreditsPage;
  campaignTrail_temp.credits = "<button onclick='ky2023CreditsPage()'>Credits</button> 2023 Kentucky Governor by Codex for shivam-BG. PA Gov-style presentation inspired by ItsAstronomical's 2022 PA Gov release.";
  campaignTrail_temp.SelectText = "Please select the election you will run in:";
  campaignTrail_temp.CandidText = "Please select your candidate:";
  campaignTrail_temp.VpText = "Please select your running mate:";
  campaignTrail_temp.PartyText = "Party:";
  campaignTrail_temp.HomeStateText = "Home State:";
  campaignTrail_temp.VisitText = "You have chosen to visit ";
  campaignTrail_temp.VisitText2 = " -- is this correct?";
  campaignTrail_temp.ElectionPopup = "Election night has arrived in Kentucky. Watch the county returns and see whether Beshear's crossover coalition survives or Cameron's partisan tide takes over.";
  campaignTrail_temp.WinPopup = "Congratulations, you won the Kentucky governorship.";
  campaignTrail_temp.LosePopup = "Sorry, you came up short in Kentucky.";
  campaignTrail_temp.SelAnsContText = "Please select an answer before continuing.";
  campaignTrail_temp.finalPercentDigits = 2;
  campaignTrail_temp.statePercentDigits = 2;
  campaignTrail_temp.modBoxTheme = {
    header_color: "#28318f",
    header_text_color: "#ffffff",
    description_text_color: "#111827",
    description_background_color: "#f4f4f4",
    main_color: "#646fd4",
    secondary_color: "#8b4e52",
    ui_text_color: "#111827"
  };

  if (root.document && !root.document.getElementById("ky2023_theme_style")) {
    const style = root.document.createElement("style");
    style.id = "ky2023_theme_style";
    style.textContent = [
      "body{background:#646fd4;}",
      ".container,.content_box,.content_single,#game_window{background:#646fd4 !important;}",
      "#game_window .game_header{background:#28318f !important;color:#fff;border-bottom:4px solid #ffffff;}",
      "#game_window .game_header h2{font-size:58px;line-height:1.05;margin:10px 0 8px;font-style:italic;}",
      "#game_window #wittyquote{font-size:28px;}",
      "#game_window .inner_window,#game_window .inner_window_front,#game_window .inner_inner_window{background:#f4f4f4;color:#000;border:2px solid #c9c9c9;}",
      "#game_window #below_header{background:#646fd4;}",
      "#campaign_sign p{font-family:Arial Black,Impact,Arial,sans-serif;font-weight:900;}",
      "#game_window button{border-radius:0;font-size:18px;}"
    ].join("\n");
    root.document.head.appendChild(style);
  }

  campaignTrail_temp.soundtrack = MOD.soundtrack;
  campaignTrail_temp.musicOn = false;
  campaignTrail_temp.musicSrc = "";
  campaignTrail_temp.music_list = MOD.soundtrack.map((track, index) => ({
    id: index + 1,
    name: `${track.artist} - ${track.title}`,
    display_name: `${track.title} - ${track.artist}`,
    query: `${track.artist} ${track.title} official audio`,
    url: "",
    note: track.mood
  }));

  root.KY2023_ASSET_BASE = MOD.github_raw_base;
  root.KY2023_CODE2_URL = MOD.code2_url;
  root.KY2023_BOOTSTRAP = root.KY2023_BOOTSTRAP || {};

  root.KY2023_BOOTSTRAP.loadCode2 = function () {
    if (root.KY2023_applyMod) {
      root.KY2023_applyMod({ rerender: true });
      return Promise.resolve(true);
    }
    const pastedCode2 = root.document && root.document.getElementById("codeset2") && root.document.getElementById("codeset2").value;
    if (pastedCode2 && /KY2023_MOD|2023 Kentucky Governor/.test(pastedCode2)) {
      try {
        (0, eval)(pastedCode2);
        if (root.KY2023_applyMod) root.KY2023_applyMod({ rerender: true });
        return Promise.resolve(true);
      } catch (error) {
        console.error("[KY2023] Pasted Code 2 failed", error);
      }
    }
    if (root.KY2023_BOOTSTRAP.loading) return root.KY2023_BOOTSTRAP.loading;
    root.KY2023_BOOTSTRAP.loading = fetch(root.KY2023_CODE2_URL, { cache: "no-store" })
      .then((response) => {
        if (!response.ok) throw new Error(`Could not fetch Code 2: ${response.status}`);
        return response.text();
      })
      .then((code) => {
        (0, eval)(code);
        if (root.KY2023_applyMod) root.KY2023_applyMod({ rerender: true });
        return true;
      })
      .catch((error) => {
        console.error("[KY2023] Code 2 fallback failed", error);
        root.KY2023_BOOTSTRAP.loading = null;
        return false;
      });
    return root.KY2023_BOOTSTRAP.loading;
  };

  function ky2023NeedsRepair() {
    if (!campaignTrail_temp.candidate_id) return false;
    const firstQuestion = campaignTrail_temp.questions_json && campaignTrail_temp.questions_json[0];
    const firstText = firstQuestion && firstQuestion.fields ? String(firstQuestion.fields.description || "") : "";
    const bodyText = root.document && root.document.body ? root.document.body.innerText || "" : "";
    return !/rematch-free 2023 race|Kentucky/i.test(firstText) ||
      /2016 election|Clinton\s+Booker|Clinton Foundation|First Lady of Arkansas/i.test(bodyText);
  }

  if (!root.KY2023_BOOTSTRAP.guard) {
    root.KY2023_BOOTSTRAP.guard = root.setInterval(function () {
      if (ky2023NeedsRepair()) root.KY2023_BOOTSTRAP.loadCode2();
      if (root.KY2023_applyMod && campaignTrail_temp.candidate_id) root.KY2023_applyMod({ quiet: true });
    }, 900);
  }
})();
