// 2023 Kentucky Governor - Code 1
// Paste this into the New Campaign Trail Code 1 box, then paste Code 2.
// Soundtrack entries are metadata/search cues only; no copyrighted audio is bundled.
(function () {
  const root = typeof window !== "undefined" ? window : globalThis;
  root.campaignTrail_temp = root.campaignTrail_temp || {};
  const campaignTrail_temp = root.campaignTrail_temp;

  const MOD = {
  "id": 20231107,
  "loader_slot": 20,
  "title": "2023 Kentucky Governor",
  "subtitle": "Beshear vs. Cameron",
  "creator": "Generated by Codex for a New Campaign Trail-style mod",
  "github_raw_base": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main",
  "code2_url": "https://raw.githubusercontent.com/shivam-BG/ky-2023-governor-nct-mod/main/code2_2023_ky_governor.js",
  "soundtrack": [
    {
      "title": "Last Night",
      "artist": "Morgan Wallen",
      "year": 2023,
      "mood": "rural radio / red-county ad break"
    },
    {
      "title": "Flowers",
      "artist": "Miley Cyrus",
      "year": 2023,
      "mood": "upbeat statewide bumper"
    },
    {
      "title": "Kill Bill",
      "artist": "SZA",
      "year": 2023,
      "mood": "metro turnout montage"
    },
    {
      "title": "Fast Car",
      "artist": "Luke Combs",
      "year": 2023,
      "mood": "working-class crossover"
    },
    {
      "title": "Need a Favor",
      "artist": "Jelly Roll",
      "year": 2023,
      "mood": "recovery / faith / opioid-question bed"
    },
    {
      "title": "I Remember Everything",
      "artist": "Zach Bryan feat. Kacey Musgraves",
      "year": 2023,
      "mood": "closing stretch reflection"
    },
    {
      "title": "Dance the Night",
      "artist": "Dua Lipa",
      "year": 2023,
      "mood": "light election-night menu"
    },
    {
      "title": "vampire",
      "artist": "Olivia Rodrigo",
      "year": 2023,
      "mood": "attack-ad sting"
    },
    {
      "title": "Paint The Town Red",
      "artist": "Doja Cat",
      "year": 2023,
      "mood": "Cameron momentum cue"
    },
    {
      "title": "What Was I Made For?",
      "artist": "Billie Eilish",
      "year": 2023,
      "mood": "melancholy loss ending"
    },
    {
      "title": "Barbie World",
      "artist": "Nicki Minaj & Ice Spice with Aqua",
      "year": 2023,
      "mood": "youth-turnout gag slot"
    },
    {
      "title": "Rich Men North of Richmond",
      "artist": "Oliver Anthony Music",
      "year": 2023,
      "mood": "anti-establishment rural cue"
    }
  ],
  "sources": {
    "2023 Kentucky gubernatorial county results": "https://en.wikipedia.org/wiki/2023_Kentucky_gubernatorial_election",
    "2020 Kentucky presidential county results": "https://en.wikipedia.org/wiki/2020_United_States_presidential_election_in_Kentucky",
    "U.S. county GeoJSON boundaries": "https://github.com/plotly/datasets/blob/master/geojson-counties-fips.json",
    "AP Beshear path analysis": "https://apnews.com/article/f942a360de22975335a1406f1fdd9ad4"
  }
};
  root.KY2023_CODE1 = MOD;

  campaignTrail_temp.election_id = 20;
  campaignTrail_temp.election_json = [
  {
    "model": "campaign_trail.election",
    "pk": 20,
    "fields": {
      "year": 2023,
      "display_year": "2023 Kentucky Governor",
      "summary": "<p>Incumbent Democratic Governor Andy Beshear seeks a second term in a state Donald Trump carried by about 26 points in 2020. Republican Attorney General Daniel Cameron tries to nationalize the race around Biden, inflation, crime, schools, and conservative control of Frankfort. Beshear counters with disaster response, economic development, abortion exceptions, and a Kentucky-first personal brand.</p>",
      "image_url": "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20420%20300%22%3E%0A%3Cdefs%3E%0A%3ClinearGradient%20id=%22g%22%20x1=%220%22%20y1=%220%22%20x2=%221%22%20y2=%221%22%3E%0A%3Cstop%20offset=%220%22%20stop-color=%22#263b63%22/%3E%0A%3Cstop%20offset=%221%22%20stop-color=%22#1f7a5a%22/%3E%0A%3C/linearGradient%3E%0A%3C/defs%3E%0A%3Crect%20width=%22420%22%20height=%22300%22%20rx=%220%22%20fill=%22#f8fafc%22/%3E%0A%3Crect%20x=%2218%22%20y=%2218%22%20width=%22384%22%20height=%22264%22%20rx=%220%22%20fill=%22url(#g)%22/%3E%0A%3Ccircle%20cx=%22210%22%20cy=%22118%22%20r=%2258%22%20fill=%22rgba(255,255,255,0.24)%22/%3E%0A%3Ctext%20x=%22210%22%20y=%22135%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2252%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EKY%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22214%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2228%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EKentucky%202023%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22246%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2218%22%20fill=%22#f8fafc%22%3EGovernor%20Election%3C/text%3E%0A%3C/svg%3E",
      "winning_electoral_vote_number": 675,
      "advisor_url": "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20420%20300%22%3E%0A%3Cdefs%3E%0A%3ClinearGradient%20id=%22g%22%20x1=%220%22%20y1=%220%22%20x2=%221%22%20y2=%221%22%3E%0A%3Cstop%20offset=%220%22%20stop-color=%22#263b63%22/%3E%0A%3Cstop%20offset=%221%22%20stop-color=%22#1f7a5a%22/%3E%0A%3C/linearGradient%3E%0A%3C/defs%3E%0A%3Crect%20width=%22420%22%20height=%22300%22%20rx=%220%22%20fill=%22#f8fafc%22/%3E%0A%3Crect%20x=%2218%22%20y=%2218%22%20width=%22384%22%20height=%22264%22%20rx=%220%22%20fill=%22url(#g)%22/%3E%0A%3Ccircle%20cx=%22210%22%20cy=%22118%22%20r=%2258%22%20fill=%22rgba(255,255,255,0.24)%22/%3E%0A%3Ctext%20x=%22210%22%20y=%22135%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2252%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EKY%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22214%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2228%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EKentucky%202023%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22246%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2218%22%20fill=%22#f8fafc%22%3EGovernor%20Election%3C/text%3E%0A%3C/svg%3E",
      "recommended_reading": "<ul><li>2023 Kentucky gubernatorial election county results</li><li>2020 Kentucky presidential county margins</li><li>AP analysis of Beshear's 2023 path through Trump country</li></ul>",
      "has_visits": 0,
      "no_electoral_majority_image": "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20420%20300%22%3E%0A%3Cdefs%3E%0A%3ClinearGradient%20id=%22g%22%20x1=%220%22%20y1=%220%22%20x2=%221%22%20y2=%221%22%3E%0A%3Cstop%20offset=%220%22%20stop-color=%22#263b63%22/%3E%0A%3Cstop%20offset=%221%22%20stop-color=%22#1f7a5a%22/%3E%0A%3C/linearGradient%3E%0A%3C/defs%3E%0A%3Crect%20width=%22420%22%20height=%22300%22%20rx=%220%22%20fill=%22#f8fafc%22/%3E%0A%3Crect%20x=%2218%22%20y=%2218%22%20width=%22384%22%20height=%22264%22%20rx=%220%22%20fill=%22url(#g)%22/%3E%0A%3Ccircle%20cx=%22210%22%20cy=%22118%22%20r=%2258%22%20fill=%22rgba(255,255,255,0.24)%22/%3E%0A%3Ctext%20x=%22210%22%20y=%22135%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2252%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EKY%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22214%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2228%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EKentucky%202023%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22246%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2218%22%20fill=%22#f8fafc%22%3EGovernor%20Election%3C/text%3E%0A%3C/svg%3E"
    }
  }
];
  campaignTrail_temp.candidate_json = [
  {
    "model": "campaign_trail.candidate",
    "pk": 201,
    "fields": {
      "first_name": "Andy",
      "last_name": "Beshear",
      "election": 20,
      "party": "Democratic",
      "state": "Kentucky",
      "priority": 1,
      "description": "<p>Andy Beshear is the incumbent Democratic governor, trying to win a second term in a heavily Republican state by leaning on disaster response, economic development, abortion exceptions, teacher support, and a carefully local brand.</p>",
      "color_hex": "#2f6fdd",
      "secondary_color_hex": "#9cc5ff",
      "is_active": 1,
      "image_url": "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20420%20300%22%3E%0A%3Cdefs%3E%0A%3ClinearGradient%20id=%22g%22%20x1=%220%22%20y1=%220%22%20x2=%221%22%20y2=%221%22%3E%0A%3Cstop%20offset=%220%22%20stop-color=%22#225ea8%22/%3E%0A%3Cstop%20offset=%221%22%20stop-color=%22#4f9fd9%22/%3E%0A%3C/linearGradient%3E%0A%3C/defs%3E%0A%3Crect%20width=%22420%22%20height=%22300%22%20rx=%220%22%20fill=%22#f8fafc%22/%3E%0A%3Crect%20x=%2218%22%20y=%2218%22%20width=%22384%22%20height=%22264%22%20rx=%220%22%20fill=%22url(#g)%22/%3E%0A%3Ccircle%20cx=%22210%22%20cy=%22118%22%20r=%2258%22%20fill=%22rgba(255,255,255,0.24)%22/%3E%0A%3Ctext%20x=%22210%22%20y=%22135%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2252%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EAB%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22214%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2228%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EAndy%20Beshear%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22246%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2218%22%20fill=%22#f8fafc%22%3EDemocratic%20Governor%3C/text%3E%0A%3C/svg%3E",
      "electoral_victory_message": "<h3>Beshear wins reelection.</h3><p>Kentucky has split its ticket again, rewarding a governor whose personal brand outran federal partisanship.</p>",
      "electoral_loss_message": "<h3>Beshear falls short.</h3><p>Cameron nationalized the race just enough to restore Kentucky's Republican gravity.</p>",
      "no_electoral_majority_message": "<h3>Too close to call.</h3><p>Kentucky is staring at another county-by-county nail-biter.</p>",
      "description_as_running_mate": "<p>Andy Beshear is the top of the Democratic ticket.</p>",
      "candidate_score": 1.0
    }
  },
  {
    "model": "campaign_trail.candidate",
    "pk": 200,
    "fields": {
      "first_name": "Daniel",
      "last_name": "Cameron",
      "election": 20,
      "party": "Republican",
      "state": "Kentucky",
      "priority": 2,
      "description": "<p>Daniel Cameron is Kentucky's Republican attorney general, running on conservative change, affordability, public safety, education fights, and the argument that Beshear is still tied to national Democrats.</p>",
      "color_hex": "#c83e3a",
      "secondary_color_hex": "#f4aaa3",
      "is_active": 1,
      "image_url": "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20420%20300%22%3E%0A%3Cdefs%3E%0A%3ClinearGradient%20id=%22g%22%20x1=%220%22%20y1=%220%22%20x2=%221%22%20y2=%221%22%3E%0A%3Cstop%20offset=%220%22%20stop-color=%22#b91c1c%22/%3E%0A%3Cstop%20offset=%221%22%20stop-color=%22#ef6b4a%22/%3E%0A%3C/linearGradient%3E%0A%3C/defs%3E%0A%3Crect%20width=%22420%22%20height=%22300%22%20rx=%220%22%20fill=%22#f8fafc%22/%3E%0A%3Crect%20x=%2218%22%20y=%2218%22%20width=%22384%22%20height=%22264%22%20rx=%220%22%20fill=%22url(#g)%22/%3E%0A%3Ccircle%20cx=%22210%22%20cy=%22118%22%20r=%2258%22%20fill=%22rgba(255,255,255,0.24)%22/%3E%0A%3Ctext%20x=%22210%22%20y=%22135%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2252%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EDC%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22214%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2228%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EDaniel%20Cameron%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22246%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2218%22%20fill=%22#f8fafc%22%3ERepublican%20Attorney%20General%3C/text%3E%0A%3C/svg%3E",
      "electoral_victory_message": "<h3>Cameron wins.</h3><p>Republicans have broken the Beshear coalition and unified Frankfort behind conservative control.</p>",
      "electoral_loss_message": "<h3>Cameron loses.</h3><p>Beshear's personal appeal, disaster response, and suburban crossover vote survived the partisan headwinds.</p>",
      "no_electoral_majority_message": "<h3>Too close to call.</h3><p>The governor race is balanced on a handful of counties.</p>",
      "description_as_running_mate": "<p>Daniel Cameron is the top of the Republican ticket.</p>",
      "candidate_score": 1.0
    }
  },
  {
    "model": "campaign_trail.candidate",
    "pk": 209,
    "fields": {
      "first_name": "Jacqueline",
      "last_name": "Coleman",
      "election": 20,
      "party": "Democratic",
      "state": "Kentucky",
      "priority": 3,
      "description": "'",
      "color_hex": "#2f6fdd",
      "secondary_color_hex": "#9cc5ff",
      "is_active": 0,
      "image_url": "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20420%20300%22%3E%0A%3Cdefs%3E%0A%3ClinearGradient%20id=%22g%22%20x1=%220%22%20y1=%220%22%20x2=%221%22%20y2=%221%22%3E%0A%3Cstop%20offset=%220%22%20stop-color=%22#2563eb%22/%3E%0A%3Cstop%20offset=%221%22%20stop-color=%22#7c3aed%22/%3E%0A%3C/linearGradient%3E%0A%3C/defs%3E%0A%3Crect%20width=%22420%22%20height=%22300%22%20rx=%220%22%20fill=%22#f8fafc%22/%3E%0A%3Crect%20x=%2218%22%20y=%2218%22%20width=%22384%22%20height=%22264%22%20rx=%220%22%20fill=%22url(#g)%22/%3E%0A%3Ccircle%20cx=%22210%22%20cy=%22118%22%20r=%2258%22%20fill=%22rgba(255,255,255,0.24)%22/%3E%0A%3Ctext%20x=%22210%22%20y=%22135%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2252%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EJC%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22214%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2228%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3EJacqueline%20Coleman%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22246%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2218%22%20fill=%22#f8fafc%22%3ELieutenant%20Governor%3C/text%3E%0A%3C/svg%3E",
      "electoral_victory_message": "'",
      "electoral_loss_message": "'",
      "no_electoral_majority_message": "'",
      "description_as_running_mate": "<p>Jacqueline Coleman is the incumbent lieutenant governor, a former teacher, and a strong validator on education, families, and continuity.</p>",
      "candidate_score": 0.0
    }
  },
  {
    "model": "campaign_trail.candidate",
    "pk": 204,
    "fields": {
      "first_name": "Robby",
      "last_name": "Mills",
      "election": 20,
      "party": "Republican",
      "state": "Kentucky",
      "priority": 4,
      "description": "'",
      "color_hex": "#c83e3a",
      "secondary_color_hex": "#f4aaa3",
      "is_active": 0,
      "image_url": "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20420%20300%22%3E%0A%3Cdefs%3E%0A%3ClinearGradient%20id=%22g%22%20x1=%220%22%20y1=%220%22%20x2=%221%22%20y2=%221%22%3E%0A%3Cstop%20offset=%220%22%20stop-color=%22#991b1b%22/%3E%0A%3Cstop%20offset=%221%22%20stop-color=%22#d97706%22/%3E%0A%3C/linearGradient%3E%0A%3C/defs%3E%0A%3Crect%20width=%22420%22%20height=%22300%22%20rx=%220%22%20fill=%22#f8fafc%22/%3E%0A%3Crect%20x=%2218%22%20y=%2218%22%20width=%22384%22%20height=%22264%22%20rx=%220%22%20fill=%22url(#g)%22/%3E%0A%3Ccircle%20cx=%22210%22%20cy=%22118%22%20r=%2258%22%20fill=%22rgba(255,255,255,0.24)%22/%3E%0A%3Ctext%20x=%22210%22%20y=%22135%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2252%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3ERM%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22214%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2228%22%20font-weight=%22700%22%20fill=%22#ffffff%22%3ERobby%20Mills%3C/text%3E%0A%3Ctext%20x=%22210%22%20y=%22246%22%20text-anchor=%22middle%22%20font-family=%22Arial,%20Helvetica,%20sans-serif%22%20font-size=%2218%22%20fill=%22#f8fafc%22%3EState%20Senator%3C/text%3E%0A%3C/svg%3E",
      "electoral_victory_message": "'",
      "electoral_loss_message": "'",
      "no_electoral_majority_message": "'",
      "description_as_running_mate": "<p>Robby Mills is a Republican state senator and Cameron's running mate, useful for western Kentucky, legislative relationships, and conservative base reassurance.</p>",
      "candidate_score": 0.0
    }
  }
];
  campaignTrail_temp.running_mate_json = [
  {
    "model": "campaign_trail.running_mate",
    "pk": 72001,
    "fields": {
      "candidate": 201,
      "running_mate": 209
    }
  },
  {
    "model": "campaign_trail.running_mate",
    "pk": 72002,
    "fields": {
      "candidate": 200,
      "running_mate": 204
    }
  }
];
  campaignTrail_temp.opponents_default_json = [
  {
    "election": 20,
    "candidates": [
      201,
      200
    ]
  }
];
  campaignTrail_temp.opponents_weighted_json = [
  {
    "election": 20,
    "candidates": [
      201,
      200
    ]
  }
];
  campaignTrail_temp.temp_election_list = [
  {
    "id": 20,
    "year": 2023,
    "is_premium": 0,
    "display_year": "2023 KY Governor"
  }
];
  campaignTrail_temp.candidate_dropout_json = [];
  campaignTrail_temp.show_premium = true;
  campaignTrail_temp.premier_ab_test_version = -1;

  campaignTrail_temp.credits = "2023 Kentucky Governor mod generated by Codex. County results from public 2023 KY gubernatorial and 2020 presidential tables; issue maps are modelled scenario scores.";
  campaignTrail_temp.SelectText = "Please select the election you will run in:";
  campaignTrail_temp.CandidText = "Please select your candidate:";
  campaignTrail_temp.VpText = "Please select your running mate:";
  campaignTrail_temp.PartyText = "Party:";
  campaignTrail_temp.HomeStateText = "Home State:";
  campaignTrail_temp.VisitText = "You have chosen to visit ";
  campaignTrail_temp.VisitText2 = " -- is this correct?";
  campaignTrail_temp.ElectionPopup = "Election night has arrived in Kentucky. Watch the county returns and see whether Beshear's crossover coalition survives or Cameron's partisan tide takes over.";
  campaignTrail_temp.WinPopup = "Congratulations, you won the Kentucky governorship.";
  campaignTrail_temp.LosePopup = "Sorry, you came up short in Kentucky.";
  campaignTrail_temp.SelAnsContText = "Please select an answer before continuing.";
  campaignTrail_temp.finalPercentDigits = 2;
  campaignTrail_temp.statePercentDigits = 2;
  campaignTrail_temp.modBoxTheme = {
    header_color: "#263b63",
    header_text_color: "#ffffff",
    description_text_color: "#111827",
    description_background_color: "#f8fafc",
    main_color: "#ffffff",
    secondary_color: "#e8edf5",
    ui_text_color: "#111827"
  };

  campaignTrail_temp.soundtrack = MOD.soundtrack;
  campaignTrail_temp.musicOn = false;
  campaignTrail_temp.musicSrc = "";
  campaignTrail_temp.music_list = MOD.soundtrack.map((track, index) => ({
    id: index + 1,
    name: `${track.artist} - ${track.title}`,
    display_name: `${track.title} - ${track.artist}`,
    query: `${track.artist} ${track.title} official audio`,
    url: "",
    note: track.mood
  }));

  root.KY2023_ASSET_BASE = MOD.github_raw_base;
  root.KY2023_CODE2_URL = MOD.code2_url;
  root.KY2023_BOOTSTRAP = root.KY2023_BOOTSTRAP || {};

  root.KY2023_BOOTSTRAP.loadCode2 = function () {
    if (root.KY2023_applyMod) {
      root.KY2023_applyMod({ rerender: true });
      return Promise.resolve(true);
    }
    if (root.KY2023_BOOTSTRAP.loading) return root.KY2023_BOOTSTRAP.loading;
    root.KY2023_BOOTSTRAP.loading = fetch(root.KY2023_CODE2_URL, { cache: "no-store" })
      .then((response) => {
        if (!response.ok) throw new Error(`Could not fetch Code 2: ${response.status}`);
        return response.text();
      })
      .then((code) => {
        (0, eval)(code);
        if (root.KY2023_applyMod) root.KY2023_applyMod({ rerender: true });
        return true;
      })
      .catch((error) => {
        console.error("[KY2023] Code 2 fallback failed", error);
        root.KY2023_BOOTSTRAP.loading = null;
        return false;
      });
    return root.KY2023_BOOTSTRAP.loading;
  };

  function ky2023NeedsRepair() {
    if (!campaignTrail_temp.candidate_id) return false;
    const firstQuestion = campaignTrail_temp.questions_json && campaignTrail_temp.questions_json[0];
    const firstText = firstQuestion && firstQuestion.fields ? String(firstQuestion.fields.description || "") : "";
    const bodyText = root.document && root.document.body ? root.document.body.innerText || "" : "";
    return !/rematch-free 2023 race|Kentucky/i.test(firstText) ||
      /2016 election|Clinton\s+Booker|Clinton Foundation|First Lady of Arkansas/i.test(bodyText);
  }

  if (!root.KY2023_BOOTSTRAP.guard) {
    root.KY2023_BOOTSTRAP.guard = root.setInterval(function () {
      if (ky2023NeedsRepair()) root.KY2023_BOOTSTRAP.loadCode2();
      if (root.KY2023_applyMod && campaignTrail_temp.candidate_id) root.KY2023_applyMod({ quiet: true });
    }, 900);
  }
})();
